# Generated by Django 6.0.6 on 2026-07-23 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_status', models.CharField(choices=[('IN_STOCK', 'Em Estoque'), ('EXHAUSTED', 'Esgotado')], default='EXHAUSTED', max_length=20)),
                ('name_product', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('stock_quantity', models.IntegerField(default=0)),
                ('sku', models.CharField(max_length=50, unique=True)),
                ('product_image', models.ImageField(upload_to='products/')),
                ('seller_name', models.CharField(blank=True, max_length=200, null=True)),
                ('company_name', models.CharField(blank=True, max_length=200, null=True)),
                ('company_number', models.CharField(blank=True, max_length=15, null=True)),
                ('company_ender', models.CharField(blank=True, max_length=200, null=True)),
                ('company_email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
    ]
