# Generated by Django 6.0.6 on 2026-07-27 21:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_stockmovement'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('number', models.CharField(blank=True, max_length=15, null=True)),
                ('ender', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='company_images/')),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='company_email',
        ),
        migrations.RemoveField(
            model_name='product',
            name='company_ender',
        ),
        migrations.RemoveField(
            model_name='product',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='product',
            name='company_number',
        ),
        migrations.RemoveField(
            model_name='product',
            name='seller_name',
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='seller_images/')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stock.company')),
            ],
        ),
    ]
