# Generated by Django 6.1 on 2026-08-23 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_product_company_product_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price_restocking',
            field=models.FloatField(default=0, verbose_name='Preço para reabastecer'),
        ),
        migrations.AddField(
            model_name='product',
            name='profits',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='profits',
            field=models.FloatField(default=0, verbose_name='Lucro da Venda'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='date_moved',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data da venda'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='quantity_out',
            field=models.IntegerField(verbose_name='Quantidades vendidas'),
        ),
    ]
