# Generated by Django 6.1 on 2026-08-23 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0005_product_price_restocking_product_profits_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='profits',
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(default=0, verbose_name='Preço de venda (R$)'),
        ),
    ]
